name: 'PR reviewer request'
description: 'Request reviewers for a PR and add comment on the PR'
inputs:
  repo_name:
    description: 'Name of the repo(owner/repo_name combination)'
    required: true
  pr_number:
    description: 'Number of the PR'
    required: true
  pr_reviewers:
    description: 'List of reviewers (comma separated)'
    required: true
  DO_COMMENT:
    description: 'Add comment on the PR, true/false'
    required: true
  github-token:
    description: 'Github token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
