name: 'PR reviewer request'
description: 'Request reviewers for a PR and add comment on the PR'
inputs:
  repo_name:
    description: 'Name of the repo(owner/repo_name combination)'
    required: true
  pr_number:
    description: 'Number of the PR'
    required: true
  pr_reviewers:
    description: 'List of reviewers (comma separated)'
    required: true
  do_comment:
    description: 'Add comment on the PR, true/false'
    required: true
  github_token:
    description: 'Github token'
    required: true
  custom_comment:
    description: 'Custom message to be added in the comment, if do_comment is true and add reviewers with @ in the message as well. Ex: @reviewer1, @reviewer2'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
